version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: "Test"
          command: echo "test complete"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
     
